name: Staging Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, opcache

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [remote]
            type = ${{ secrets.RCLONE_TYPE }}
            host = ${{ secrets.SERVER_HOST }}
            port = ${{ secrets.SERVER_PORT }}
            user = ${{ secrets.DEPLOY_USER }}
            pass = ${{ secrets.DEPLOY_PASS }}
            tls = ${{ secrets.RCLONE_TLS }}
            explicit_tls = ${{ secrets.RCLONE_EXPLICIT_TLS }}
          disable_base64: true

      - name: Install project dependencies
        run: composer install --no-dev --no-progress --no-suggest

      - name: Install theme dependencies and compile assets
        run: |
          cd ${{ secrets.THEME_DIR }}
          composer install --no-dev --no-progress --no-suggest
          npm install --silent --no-progress
          npm run build

      - name: Deploy Via Rclone
        run: rclone sync --quiet --transfers 4 --checkers 4 --exclude-from=".deploy-exclude" --stats-one-line ./ remote:${{ secrets.SERVER_PATH }}